package com.avyeyes.controllers


case class ReportData(
  submitterEmail: String,
  submitterExperience: String,
  areaName: String,
  avalancheDate: String,
  avalancheType: String,
  trigger: String,
  triggerModifier: String,
  interface: String,
  rSize: Double,
  dSize: Double,
  elevation: Int,
  slopeAspect: String,
  slopeAngle: Int,
  recentSnow: Int,
  recentWindSpeed: String,
  recentWindDirection: String,
  numCaught: Int,
  numPartiallyBuried: Int,
  numFullyBuried: Int,
  numInjured: Int,
  numKilled: Int,
  modeOfTravel: String,
  comments: String,
  viewable: Boolean,
  extId: String,
  editKey: String,
  latitude: Double,
  longitude: Double,
  perimeter: String
)

//  val reportForm: Form[ReportData] = Form(
//    mapping(
//      "reportSubmitterEmail" -> email,
//      "reportSubmitterExperience" -> text,
//      "reportAreaName" -> text,
//      "reportAvalancheDate" -> text,
//      "reportAvalancheType" -> text,
//      "reportTrigger" -> text,
//      "reportTriggerModifier" -> text,
//      "reportInterface" -> text,
//      "reportRsize" -> number,
//      "reportDsize" -> number,
//      "reportElevation" -> number,
//      "reportSlopeAspect" -> text,
//      "reportSlopeAngle" -> number,
//      "reportRecentSnow" -> number,
//      "reportRecentWindSpeed" -> number,
//      "reportRecentWindDirection" -> text,
//      "reportNumCaught" -> number,
//      "reportNumPartiallyBuried" -> number,
//      "reportNumFullyBuried" -> number,
//      "reportNumInjured" -> number,
//      "reportNumKilled" -> number,
//      "reportModeOfTravel" -> text,
//      "reportComments" -> text,
//      "reportViewable" -> boolean,
//      "reportExtId" -> text,
//      "reportEditKey" -> text,
//      "reportAvalancheLatitude" -> number,
//      "reportAvalancheLongitude" -> number,
//      "reportPathPerimeter" -> text
//    )(ReportData.apply)(ReportData.unapply)
//  )