package com.avyeyes.model.enums

object AvalancheTrigger extends DataCodeEnum {
  val NATURAL = new DataCodeVal(1, "N", "Natural trigger")
  val CORNICE_FALL_NATURAL = new DataCodeVal(2, "NC", "Cornice fall")
  val EARTHQUAKE = new DataCodeVal(3, "NE", "Earthquake")
  val ICE_FALL = new DataCodeVal(4, "NI", "Ice fall")
  val LOOSE_SNOW = new DataCodeVal(5, "NL", "Loose snow avalanche")
  val SLAB = new DataCodeVal(6, "NS", "Slab avalanche")
  val ROCK_FALL = new DataCodeVal(7, "NR", "Rock fall")
  val UNCLASSIFIED_NATURAL = new DataCodeVal(8, "NO", "Unclassified natural trigger")
  val ARTILLERY = new DataCodeVal(9, "AA", "Artillery")
  val HAND_PLACED_EXPLOSIVE = new DataCodeVal(10, "AE", "Thrown or placed explosive")
  val AVALAUNCHER = new DataCodeVal(11, "AL", "Avalauncher")
  val AIR_BLAST = new DataCodeVal(12, "AB", "Above snow air blast")
  val CORNICE_FALL_ARTIFICIAL = new DataCodeVal(13, "AC", "Cornice fall from human or explosive")
  val GAS_EXPLODER = new DataCodeVal(14, "AX", "Gas exploder")
  val HELI_PLACED_EXPLOSIVE = new DataCodeVal(15, "AH", "Explosive placed from helicopter")
  val PRE_PLACED_EXPLOSIVE = new DataCodeVal(16, "AP", "Pre-placed remote explosive")
  val WILDLIFE = new DataCodeVal(17, "AW", "Wildlife")
  val UNKNOWN_ARTIFICIAL = new DataCodeVal(18, "AU", "Unknown artificial trigger")
  val UNCLASSIFIED_ARTIFICIAL = new DataCodeVal(19, "AO", "Unclassified artificial trigger")
  val SNOWMOBILE = new DataCodeVal(20, "AM", "Snowmobile")
  val SNOWCAT = new DataCodeVal(21, "AK", "Snowcat")
  val VEHCILE = new DataCodeVal(22, "AV", "Vehicle")
  val SKIER = new DataCodeVal(23, "AS", "Skier")
  val SNOWBOARDER = new DataCodeVal(24, "AR", "Snowboarder")
  val SNOWSHOER = new DataCodeVal(25, "AI", "Snowshoer")
  val FOOT = new DataCodeVal(26, "AF", "Foot penetration")
}